version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
    volumes:
      - .:/app
    command: >
      sh -c "npm run dev"
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=changeme123
      - MONGO_HOST=db
      - MONGO_PORT=27017
  
  db:
    image: mongo:5-focal
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=changeme123

volumes:
  mongo-data:
